// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internalservice/internalservice.proto

// i must add this so that the generated file will have a prefix  this to allow for calling

package internalservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gigservice_AccountDetails_FullMethodName = "/internalservice.gigservice/account_details"
	Gigservice_Deposit_FullMethodName        = "/internalservice.gigservice/deposit"
	Gigservice_Withdraw_FullMethodName       = "/internalservice.gigservice/withdraw"
	Gigservice_Capitalraise_FullMethodName   = "/internalservice.gigservice/capitalraise"
	Gigservice_Transfer_FullMethodName       = "/internalservice.gigservice/transfer"
	Gigservice_Sale_FullMethodName           = "/internalservice.gigservice/sale"
	Gigservice_History_FullMethodName        = "/internalservice.gigservice/history"
	Gigservice_Opening_FullMethodName        = "/internalservice.gigservice/opening"
	Gigservice_Createaccount_FullMethodName  = "/internalservice.gigservice/createaccount"
)

// GigserviceClient is the client API for Gigservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GigserviceClient interface {
	AccountDetails(ctx context.Context, in *UserAccountDataReq, opts ...grpc.CallOption) (*UserDataResp, error)
	Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error)
	Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error)
	Capitalraise(ctx context.Context, in *CapitalRaiseReq, opts ...grpc.CallOption) (*CapitalRaiseResp, error)
	Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	Sale(ctx context.Context, in *SaleReq, opts ...grpc.CallOption) (*SaleResp, error)
	History(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error)
	Opening(ctx context.Context, in *OpeningReq, opts ...grpc.CallOption) (*OpeningResp, error)
	Createaccount(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
}

type gigserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewGigserviceClient(cc grpc.ClientConnInterface) GigserviceClient {
	return &gigserviceClient{cc}
}

func (c *gigserviceClient) AccountDetails(ctx context.Context, in *UserAccountDataReq, opts ...grpc.CallOption) (*UserDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDataResp)
	err := c.cc.Invoke(ctx, Gigservice_AccountDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResp)
	err := c.cc.Invoke(ctx, Gigservice_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawResp)
	err := c.cc.Invoke(ctx, Gigservice_Withdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Capitalraise(ctx context.Context, in *CapitalRaiseReq, opts ...grpc.CallOption) (*CapitalRaiseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapitalRaiseResp)
	err := c.cc.Invoke(ctx, Gigservice_Capitalraise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResp)
	err := c.cc.Invoke(ctx, Gigservice_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Sale(ctx context.Context, in *SaleReq, opts ...grpc.CallOption) (*SaleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaleResp)
	err := c.cc.Invoke(ctx, Gigservice_Sale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) History(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResp)
	err := c.cc.Invoke(ctx, Gigservice_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Opening(ctx context.Context, in *OpeningReq, opts ...grpc.CallOption) (*OpeningResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpeningResp)
	err := c.cc.Invoke(ctx, Gigservice_Opening_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigserviceClient) Createaccount(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, Gigservice_Createaccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GigserviceServer is the server API for Gigservice service.
// All implementations must embed UnimplementedGigserviceServer
// for forward compatibility.
type GigserviceServer interface {
	AccountDetails(context.Context, *UserAccountDataReq) (*UserDataResp, error)
	Deposit(context.Context, *DepositReq) (*DepositResp, error)
	Withdraw(context.Context, *WithdrawReq) (*WithdrawResp, error)
	Capitalraise(context.Context, *CapitalRaiseReq) (*CapitalRaiseResp, error)
	Transfer(context.Context, *TransferReq) (*TransferResp, error)
	Sale(context.Context, *SaleReq) (*SaleResp, error)
	History(context.Context, *HistoryReq) (*HistoryResp, error)
	Opening(context.Context, *OpeningReq) (*OpeningResp, error)
	Createaccount(context.Context, *CreateUserReq) (*CreateUserResp, error)
	mustEmbedUnimplementedGigserviceServer()
}

// UnimplementedGigserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGigserviceServer struct{}

func (UnimplementedGigserviceServer) AccountDetails(context.Context, *UserAccountDataReq) (*UserDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountDetails not implemented")
}
func (UnimplementedGigserviceServer) Deposit(context.Context, *DepositReq) (*DepositResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedGigserviceServer) Withdraw(context.Context, *WithdrawReq) (*WithdrawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedGigserviceServer) Capitalraise(context.Context, *CapitalRaiseReq) (*CapitalRaiseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capitalraise not implemented")
}
func (UnimplementedGigserviceServer) Transfer(context.Context, *TransferReq) (*TransferResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedGigserviceServer) Sale(context.Context, *SaleReq) (*SaleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sale not implemented")
}
func (UnimplementedGigserviceServer) History(context.Context, *HistoryReq) (*HistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedGigserviceServer) Opening(context.Context, *OpeningReq) (*OpeningResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Opening not implemented")
}
func (UnimplementedGigserviceServer) Createaccount(context.Context, *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Createaccount not implemented")
}
func (UnimplementedGigserviceServer) mustEmbedUnimplementedGigserviceServer() {}
func (UnimplementedGigserviceServer) testEmbeddedByValue()                    {}

// UnsafeGigserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GigserviceServer will
// result in compilation errors.
type UnsafeGigserviceServer interface {
	mustEmbedUnimplementedGigserviceServer()
}

func RegisterGigserviceServer(s grpc.ServiceRegistrar, srv GigserviceServer) {
	// If the following call pancis, it indicates UnimplementedGigserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gigservice_ServiceDesc, srv)
}

func _Gigservice_AccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccountDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).AccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_AccountDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).AccountDetails(ctx, req.(*UserAccountDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Deposit(ctx, req.(*DepositReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Withdraw(ctx, req.(*WithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Capitalraise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapitalRaiseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Capitalraise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Capitalraise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Capitalraise(ctx, req.(*CapitalRaiseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Transfer(ctx, req.(*TransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Sale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Sale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Sale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Sale(ctx, req.(*SaleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).History(ctx, req.(*HistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Opening_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpeningReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Opening(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Opening_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Opening(ctx, req.(*OpeningReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gigservice_Createaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigserviceServer).Createaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gigservice_Createaccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigserviceServer).Createaccount(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Gigservice_ServiceDesc is the grpc.ServiceDesc for Gigservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gigservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalservice.gigservice",
	HandlerType: (*GigserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "account_details",
			Handler:    _Gigservice_AccountDetails_Handler,
		},
		{
			MethodName: "deposit",
			Handler:    _Gigservice_Deposit_Handler,
		},
		{
			MethodName: "withdraw",
			Handler:    _Gigservice_Withdraw_Handler,
		},
		{
			MethodName: "capitalraise",
			Handler:    _Gigservice_Capitalraise_Handler,
		},
		{
			MethodName: "transfer",
			Handler:    _Gigservice_Transfer_Handler,
		},
		{
			MethodName: "sale",
			Handler:    _Gigservice_Sale_Handler,
		},
		{
			MethodName: "history",
			Handler:    _Gigservice_History_Handler,
		},
		{
			MethodName: "opening",
			Handler:    _Gigservice_Opening_Handler,
		},
		{
			MethodName: "createaccount",
			Handler:    _Gigservice_Createaccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalservice/internalservice.proto",
}
