// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internalservice/internalservice.proto

// i must add this so that the generated file will have a prefix  this to allow for calling

package internalservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// here we should describe the request from the api_gateway
type CreateUserReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Globaluserid     string                 `protobuf:"bytes,1,opt,name=globaluserid,proto3" json:"globaluserid,omitempty"`
	Phonenumber      string                 `protobuf:"bytes,2,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Kycstatus        string                 `protobuf:"bytes,3,opt,name=kycstatus,proto3" json:"kycstatus,omitempty"`
	Kyclevel         string                 `protobuf:"bytes,4,opt,name=kyclevel,proto3" json:"kyclevel,omitempty"`
	Acceptterms      bool                   `protobuf:"varint,5,opt,name=acceptterms,proto3" json:"acceptterms,omitempty"`
	Transactionlimit int64                  `protobuf:"varint,6,opt,name=transactionlimit,proto3" json:"transactionlimit,omitempty"`
	Username         string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Fullname         string                 `protobuf:"bytes,9,opt,name=fullname,proto3" json:"fullname,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetGlobaluserid() string {
	if x != nil {
		return x.Globaluserid
	}
	return ""
}

func (x *CreateUserReq) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *CreateUserReq) GetKycstatus() string {
	if x != nil {
		return x.Kycstatus
	}
	return ""
}

func (x *CreateUserReq) GetKyclevel() string {
	if x != nil {
		return x.Kyclevel
	}
	return ""
}

func (x *CreateUserReq) GetAcceptterms() bool {
	if x != nil {
		return x.Acceptterms
	}
	return false
}

func (x *CreateUserReq) GetTransactionlimit() int64 {
	if x != nil {
		return x.Transactionlimit
	}
	return 0
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactionid string                 `protobuf:"bytes,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,2,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Globaluserid  string                 `protobuf:"bytes,4,opt,name=globaluserid,proto3" json:"globaluserid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{1}
}

func (x *DepositReq) GetTransactionid() string {
	if x != nil {
		return x.Transactionid
	}
	return ""
}

func (x *DepositReq) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *DepositReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DepositReq) GetGlobaluserid() string {
	if x != nil {
		return x.Globaluserid
	}
	return ""
}

type CapitalRaiseReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capitalrequired string                 `protobuf:"bytes,1,opt,name=capitalrequired,proto3" json:"capitalrequired,omitempty"`
	Creator         string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Startingdate    string                 `protobuf:"bytes,3,opt,name=startingdate,proto3" json:"startingdate,omitempty"`
	Closingdate     string                 `protobuf:"bytes,4,opt,name=closingdate,proto3" json:"closingdate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapitalRaiseReq) Reset() {
	*x = CapitalRaiseReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapitalRaiseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapitalRaiseReq) ProtoMessage() {}

func (x *CapitalRaiseReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapitalRaiseReq.ProtoReflect.Descriptor instead.
func (*CapitalRaiseReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{2}
}

func (x *CapitalRaiseReq) GetCapitalrequired() string {
	if x != nil {
		return x.Capitalrequired
	}
	return ""
}

func (x *CapitalRaiseReq) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *CapitalRaiseReq) GetStartingdate() string {
	if x != nil {
		return x.Startingdate
	}
	return ""
}

func (x *CapitalRaiseReq) GetClosingdate() string {
	if x != nil {
		return x.Closingdate
	}
	return ""
}

type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phonenumber   string                 `protobuf:"bytes,1,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Globaluserid  string                 `protobuf:"bytes,3,opt,name=globaluserid,proto3" json:"globaluserid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{3}
}

func (x *WithdrawReq) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *WithdrawReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawReq) GetGlobaluserid() string {
	if x != nil {
		return x.Globaluserid
	}
	return ""
}

type CreateWallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cashbalance   string                 `protobuf:"bytes,1,opt,name=cashbalance,proto3" json:"cashbalance,omitempty"`
	Goldbalance   string                 `protobuf:"bytes,2,opt,name=goldbalance,proto3" json:"goldbalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWallet) Reset() {
	*x = CreateWallet{}
	mi := &file_internalservice_internalservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWallet) ProtoMessage() {}

func (x *CreateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWallet.ProtoReflect.Descriptor instead.
func (*CreateWallet) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWallet) GetCashbalance() string {
	if x != nil {
		return x.Cashbalance
	}
	return ""
}

func (x *CreateWallet) GetGoldbalance() string {
	if x != nil {
		return x.Goldbalance
	}
	return ""
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Errors        *Changeseterrors       `protobuf:"bytes,3,opt,name=errors,proto3,oneof" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *CreateUserResp) GetErrors() *Changeseterrors {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Validationerror struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validationerror) Reset() {
	*x = Validationerror{}
	mi := &file_internalservice_internalservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validationerror) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validationerror) ProtoMessage() {}

func (x *Validationerror) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validationerror.ProtoReflect.Descriptor instead.
func (*Validationerror) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{6}
}

func (x *Validationerror) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Validationerror) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Changeseterrors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*Validationerror     `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Changeseterrors) Reset() {
	*x = Changeseterrors{}
	mi := &file_internalservice_internalservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Changeseterrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changeseterrors) ProtoMessage() {}

func (x *Changeseterrors) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changeseterrors.ProtoReflect.Descriptor instead.
func (*Changeseterrors) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{7}
}

func (x *Changeseterrors) GetErrors() []*Validationerror {
	if x != nil {
		return x.Errors
	}
	return nil
}

type UserAccountDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccountDataReq) Reset() {
	*x = UserAccountDataReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccountDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountDataReq) ProtoMessage() {}

func (x *UserAccountDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountDataReq.ProtoReflect.Descriptor instead.
func (*UserAccountDataReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{8}
}

func (x *UserAccountDataReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	GoldAmount    string                 `protobuf:"bytes,3,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	CashAmount    string                 `protobuf:"bytes,4,opt,name=cash_amount,json=cashAmount,proto3" json:"cash_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{9}
}

func (x *TransferReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *TransferReq) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *TransferReq) GetGoldAmount() string {
	if x != nil {
		return x.GoldAmount
	}
	return ""
}

func (x *TransferReq) GetCashAmount() string {
	if x != nil {
		return x.CashAmount
	}
	return ""
}

type SaleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	GoldAmount    string                 `protobuf:"bytes,3,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	CashAmount    string                 `protobuf:"bytes,4,opt,name=cash_amount,json=cashAmount,proto3" json:"cash_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleReq) Reset() {
	*x = SaleReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleReq) ProtoMessage() {}

func (x *SaleReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleReq.ProtoReflect.Descriptor instead.
func (*SaleReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{10}
}

func (x *SaleReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *SaleReq) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *SaleReq) GetGoldAmount() string {
	if x != nil {
		return x.GoldAmount
	}
	return ""
}

func (x *SaleReq) GetCashAmount() string {
	if x != nil {
		return x.CashAmount
	}
	return ""
}

type OpeningReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningReq) Reset() {
	*x = OpeningReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningReq) ProtoMessage() {}

func (x *OpeningReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningReq.ProtoReflect.Descriptor instead.
func (*OpeningReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{11}
}

type HistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Globaluserid  string                 `protobuf:"bytes,1,opt,name=globaluserid,proto3" json:"globaluserid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryReq) Reset() {
	*x = HistoryReq{}
	mi := &file_internalservice_internalservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReq) ProtoMessage() {}

func (x *HistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReq.ProtoReflect.Descriptor instead.
func (*HistoryReq) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryReq) GetGlobaluserid() string {
	if x != nil {
		return x.Globaluserid
	}
	return ""
}

// request i am thinking should be values like get_account_amount(account_details)
// request transfering amount from one person's wallet to another(transfer)
// if they want to see any opening they can (openings)
// if they are looking for someone selling gold (sale)
// market
// history
type UserDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoldAmount    int64                  `protobuf:"varint,1,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	CashAmount    int64                  `protobuf:"varint,2,opt,name=cash_amount,json=cashAmount,proto3" json:"cash_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataResp) Reset() {
	*x = UserDataResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResp) ProtoMessage() {}

func (x *UserDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResp.ProtoReflect.Descriptor instead.
func (*UserDataResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{13}
}

func (x *UserDataResp) GetGoldAmount() int64 {
	if x != nil {
		return x.GoldAmount
	}
	return 0
}

func (x *UserDataResp) GetCashAmount() int64 {
	if x != nil {
		return x.CashAmount
	}
	return 0
}

type SaleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successdata   *SuccessSale           `protobuf:"bytes,1,opt,name=successdata,proto3,oneof" json:"successdata,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleResp) Reset() {
	*x = SaleResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleResp) ProtoMessage() {}

func (x *SaleResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleResp.ProtoReflect.Descriptor instead.
func (*SaleResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{14}
}

func (x *SaleResp) GetSuccessdata() *SuccessSale {
	if x != nil {
		return x.Successdata
	}
	return nil
}

func (x *SaleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaleResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type SuccessSale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Goldamount    int64                  `protobuf:"varint,4,opt,name=goldamount,proto3" json:"goldamount,omitempty"`
	Moneyamount   int64                  `protobuf:"varint,5,opt,name=moneyamount,proto3" json:"moneyamount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessSale) Reset() {
	*x = SuccessSale{}
	mi := &file_internalservice_internalservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessSale) ProtoMessage() {}

func (x *SuccessSale) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessSale.ProtoReflect.Descriptor instead.
func (*SuccessSale) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{15}
}

func (x *SuccessSale) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SuccessSale) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SuccessSale) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SuccessSale) GetGoldamount() int64 {
	if x != nil {
		return x.Goldamount
	}
	return 0
}

func (x *SuccessSale) GetMoneyamount() int64 {
	if x != nil {
		return x.Moneyamount
	}
	return 0
}

// for gold every
type TransferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TranserId     string                 `protobuf:"bytes,1,opt,name=transer_id,json=transerId,proto3" json:"transer_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	GoldAmount    int64                  `protobuf:"varint,4,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	MoneyAmount   int64                  `protobuf:"varint,5,opt,name=money_amount,json=moneyAmount,proto3" json:"money_amount,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,7,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{16}
}

func (x *TransferResp) GetTranserId() string {
	if x != nil {
		return x.TranserId
	}
	return ""
}

func (x *TransferResp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferResp) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferResp) GetGoldAmount() int64 {
	if x != nil {
		return x.GoldAmount
	}
	return 0
}

func (x *TransferResp) GetMoneyAmount() int64 {
	if x != nil {
		return x.MoneyAmount
	}
	return 0
}

func (x *TransferResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// opening
type OpeningResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ClosingDate   string                 `protobuf:"bytes,2,opt,name=closing_date,json=closingDate,proto3" json:"closing_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningResp) Reset() {
	*x = OpeningResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningResp) ProtoMessage() {}

func (x *OpeningResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningResp.ProtoReflect.Descriptor instead.
func (*OpeningResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{17}
}

func (x *OpeningResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OpeningResp) GetClosingDate() string {
	if x != nil {
		return x.ClosingDate
	}
	return ""
}

type HistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []*History             `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResp) Reset() {
	*x = HistoryResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResp) ProtoMessage() {}

func (x *HistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResp.ProtoReflect.Descriptor instead.
func (*HistoryResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{18}
}

func (x *HistoryResp) GetRequest() []*History {
	if x != nil {
		return x.Request
	}
	return nil
}

type History struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpeningDate       string                 `protobuf:"bytes,1,opt,name=opening_date,json=openingDate,proto3" json:"opening_date,omitempty"`
	ClosingDate       string                 `protobuf:"bytes,2,opt,name=closing_date,json=closingDate,proto3" json:"closing_date,omitempty"`
	InitialInv        int64                  `protobuf:"varint,3,opt,name=initial_inv,json=initialInv,proto3" json:"initial_inv,omitempty"`
	Revenue           int64                  `protobuf:"varint,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	PeopleInv         int64                  `protobuf:"varint,5,opt,name=people_inv,json=peopleInv,proto3" json:"people_inv,omitempty"`
	ProfitPerShilling int64                  `protobuf:"varint,6,opt,name=profit_per_shilling,json=profitPerShilling,proto3" json:"profit_per_shilling,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_internalservice_internalservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{19}
}

func (x *History) GetOpeningDate() string {
	if x != nil {
		return x.OpeningDate
	}
	return ""
}

func (x *History) GetClosingDate() string {
	if x != nil {
		return x.ClosingDate
	}
	return ""
}

func (x *History) GetInitialInv() int64 {
	if x != nil {
		return x.InitialInv
	}
	return 0
}

func (x *History) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *History) GetPeopleInv() int64 {
	if x != nil {
		return x.PeopleInv
	}
	return 0
}

func (x *History) GetProfitPerShilling() int64 {
	if x != nil {
		return x.ProfitPerShilling
	}
	return 0
}

type DepositResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResp) Reset() {
	*x = DepositResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResp) ProtoMessage() {}

func (x *DepositResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResp.ProtoReflect.Descriptor instead.
func (*DepositResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{20}
}

func (x *DepositResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DepositResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type WithdrawResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResp) Reset() {
	*x = WithdrawResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResp) ProtoMessage() {}

func (x *WithdrawResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResp.ProtoReflect.Descriptor instead.
func (*WithdrawResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{21}
}

func (x *WithdrawResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CapitalRaiseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapitalRaiseResp) Reset() {
	*x = CapitalRaiseResp{}
	mi := &file_internalservice_internalservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapitalRaiseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapitalRaiseResp) ProtoMessage() {}

func (x *CapitalRaiseResp) ProtoReflect() protoreflect.Message {
	mi := &file_internalservice_internalservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapitalRaiseResp.ProtoReflect.Descriptor instead.
func (*CapitalRaiseResp) Descriptor() ([]byte, []int) {
	return file_internalservice_internalservice_proto_rawDescGZIP(), []int{22}
}

func (x *CapitalRaiseResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CapitalRaiseResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_internalservice_internalservice_proto protoreflect.FileDescriptor

const file_internalservice_internalservice_proto_rawDesc = "" +
	"\n" +
	"%internalservice/internalservice.proto\x12\x0finternalservice\"\x97\x02\n" +
	"\x0fcreate_user_req\x12\"\n" +
	"\fglobaluserid\x18\x01 \x01(\tR\fglobaluserid\x12 \n" +
	"\vphonenumber\x18\x02 \x01(\tR\vphonenumber\x12\x1c\n" +
	"\tkycstatus\x18\x03 \x01(\tR\tkycstatus\x12\x1a\n" +
	"\bkyclevel\x18\x04 \x01(\tR\bkyclevel\x12 \n" +
	"\vacceptterms\x18\x05 \x01(\bR\vacceptterms\x12*\n" +
	"\x10transactionlimit\x18\x06 \x01(\x03R\x10transactionlimit\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\t \x01(\tR\bfullname\"\x91\x01\n" +
	"\vdeposit_req\x12$\n" +
	"\rtransactionid\x18\x01 \x01(\tR\rtransactionid\x12 \n" +
	"\vphonenumber\x18\x02 \x01(\tR\vphonenumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\"\n" +
	"\fglobaluserid\x18\x04 \x01(\tR\fglobaluserid\"\x9d\x01\n" +
	"\x11capital_raise_req\x12(\n" +
	"\x0fcapitalrequired\x18\x01 \x01(\tR\x0fcapitalrequired\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12\"\n" +
	"\fstartingdate\x18\x03 \x01(\tR\fstartingdate\x12 \n" +
	"\vclosingdate\x18\x04 \x01(\tR\vclosingdate\"l\n" +
	"\fwithdraw_req\x12 \n" +
	"\vphonenumber\x18\x01 \x01(\tR\vphonenumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\"\n" +
	"\fglobaluserid\x18\x03 \x01(\tR\fglobaluserid\"S\n" +
	"\rcreate_wallet\x12 \n" +
	"\vcashbalance\x18\x01 \x01(\tR\vcashbalance\x12 \n" +
	"\vgoldbalance\x18\x02 \x01(\tR\vgoldbalance\"\x9f\x01\n" +
	"\x10create_user_resp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12=\n" +
	"\x06errors\x18\x03 \x01(\v2 .internalservice.changeseterrorsH\x01R\x06errors\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_errors\"A\n" +
	"\x0fvalidationerror\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x0fchangeseterrors\x128\n" +
	"\x06errors\x18\x01 \x03(\v2 .internalservice.validationerrorR\x06errors\"'\n" +
	"\x15user_account_data_req\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"~\n" +
	"\ftransfer_req\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1f\n" +
	"\vgold_amount\x18\x03 \x01(\tR\n" +
	"goldAmount\x12\x1f\n" +
	"\vcash_amount\x18\x04 \x01(\tR\n" +
	"cashAmount\"z\n" +
	"\bsale_req\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1f\n" +
	"\vgold_amount\x18\x03 \x01(\tR\n" +
	"goldAmount\x12\x1f\n" +
	"\vcash_amount\x18\x04 \x01(\tR\n" +
	"cashAmount\"\r\n" +
	"\vopening_req\"1\n" +
	"\vhistory_req\x12\"\n" +
	"\fglobaluserid\x18\x01 \x01(\tR\fglobaluserid\"R\n" +
	"\x0euser_data_resp\x12\x1f\n" +
	"\vgold_amount\x18\x01 \x01(\x03R\n" +
	"goldAmount\x12\x1f\n" +
	"\vcash_amount\x18\x02 \x01(\x03R\n" +
	"cashAmount\"\xa3\x01\n" +
	"\tsale_resp\x12D\n" +
	"\vsuccessdata\x18\x01 \x01(\v2\x1d.internalservice.success_saleH\x00R\vsuccessdata\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x01R\x06reason\x88\x01\x01B\x0e\n" +
	"\f_successdataB\t\n" +
	"\a_reason\"\x84\x01\n" +
	"\fsuccess_sale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x1e\n" +
	"\n" +
	"goldamount\x18\x04 \x01(\x03R\n" +
	"goldamount\x12 \n" +
	"\vmoneyamount\x18\x05 \x01(\x03R\vmoneyamount\"\xd8\x01\n" +
	"\rtransfer_resp\x12\x1d\n" +
	"\n" +
	"transer_id\x18\x01 \x01(\tR\ttranserId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x1f\n" +
	"\vgold_amount\x18\x04 \x01(\x03R\n" +
	"goldAmount\x12!\n" +
	"\fmoney_amount\x18\x05 \x01(\x03R\vmoneyAmount\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\a \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"I\n" +
	"\fopening_resp\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12!\n" +
	"\fclosing_date\x18\x02 \x01(\tR\vclosingDate\"B\n" +
	"\fhistory_resp\x122\n" +
	"\arequest\x18\x01 \x03(\v2\x18.internalservice.historyR\arequest\"\xd9\x01\n" +
	"\ahistory\x12!\n" +
	"\fopening_date\x18\x01 \x01(\tR\vopeningDate\x12!\n" +
	"\fclosing_date\x18\x02 \x01(\tR\vclosingDate\x12\x1f\n" +
	"\vinitial_inv\x18\x03 \x01(\x03R\n" +
	"initialInv\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x03R\arevenue\x12\x1d\n" +
	"\n" +
	"people_inv\x18\x05 \x01(\x03R\tpeopleInv\x12.\n" +
	"\x13profit_per_shilling\x18\x06 \x01(\x03R\x11profitPerShilling\"P\n" +
	"\fdeposit_resp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"Q\n" +
	"\rwithdraw_resp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"V\n" +
	"\x12capital_raise_resp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason2\xc4\x05\n" +
	"\n" +
	"gigservice\x12Z\n" +
	"\x0faccount_details\x12&.internalservice.user_account_data_req\x1a\x1f.internalservice.user_data_resp\x12F\n" +
	"\adeposit\x12\x1c.internalservice.deposit_req\x1a\x1d.internalservice.deposit_resp\x12I\n" +
	"\bwithdraw\x12\x1d.internalservice.withdraw_req\x1a\x1e.internalservice.withdraw_resp\x12W\n" +
	"\fcapitalraise\x12\".internalservice.capital_raise_req\x1a#.internalservice.capital_raise_resp\x12I\n" +
	"\btransfer\x12\x1d.internalservice.transfer_req\x1a\x1e.internalservice.transfer_resp\x12=\n" +
	"\x04sale\x12\x19.internalservice.sale_req\x1a\x1a.internalservice.sale_resp\x12F\n" +
	"\ahistory\x12\x1c.internalservice.history_req\x1a\x1d.internalservice.history_resp\x12F\n" +
	"\aopening\x12\x1c.internalservice.opening_req\x1a\x1d.internalservice.opening_resp\x12T\n" +
	"\rcreateaccount\x12 .internalservice.create_user_req\x1a!.internalservice.create_user_respB\x13Z\x11./internalserviceb\x06proto3"

var (
	file_internalservice_internalservice_proto_rawDescOnce sync.Once
	file_internalservice_internalservice_proto_rawDescData []byte
)

func file_internalservice_internalservice_proto_rawDescGZIP() []byte {
	file_internalservice_internalservice_proto_rawDescOnce.Do(func() {
		file_internalservice_internalservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internalservice_internalservice_proto_rawDesc), len(file_internalservice_internalservice_proto_rawDesc)))
	})
	return file_internalservice_internalservice_proto_rawDescData
}

var file_internalservice_internalservice_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internalservice_internalservice_proto_goTypes = []any{
	(*CreateUserReq)(nil),      // 0: internalservice.create_user_req
	(*DepositReq)(nil),         // 1: internalservice.deposit_req
	(*CapitalRaiseReq)(nil),    // 2: internalservice.capital_raise_req
	(*WithdrawReq)(nil),        // 3: internalservice.withdraw_req
	(*CreateWallet)(nil),       // 4: internalservice.create_wallet
	(*CreateUserResp)(nil),     // 5: internalservice.create_user_resp
	(*Validationerror)(nil),    // 6: internalservice.validationerror
	(*Changeseterrors)(nil),    // 7: internalservice.changeseterrors
	(*UserAccountDataReq)(nil), // 8: internalservice.user_account_data_req
	(*TransferReq)(nil),        // 9: internalservice.transfer_req
	(*SaleReq)(nil),            // 10: internalservice.sale_req
	(*OpeningReq)(nil),         // 11: internalservice.opening_req
	(*HistoryReq)(nil),         // 12: internalservice.history_req
	(*UserDataResp)(nil),       // 13: internalservice.user_data_resp
	(*SaleResp)(nil),           // 14: internalservice.sale_resp
	(*SuccessSale)(nil),        // 15: internalservice.success_sale
	(*TransferResp)(nil),       // 16: internalservice.transfer_resp
	(*OpeningResp)(nil),        // 17: internalservice.opening_resp
	(*HistoryResp)(nil),        // 18: internalservice.history_resp
	(*History)(nil),            // 19: internalservice.history
	(*DepositResp)(nil),        // 20: internalservice.deposit_resp
	(*WithdrawResp)(nil),       // 21: internalservice.withdraw_resp
	(*CapitalRaiseResp)(nil),   // 22: internalservice.capital_raise_resp
}
var file_internalservice_internalservice_proto_depIdxs = []int32{
	7,  // 0: internalservice.create_user_resp.errors:type_name -> internalservice.changeseterrors
	6,  // 1: internalservice.changeseterrors.errors:type_name -> internalservice.validationerror
	15, // 2: internalservice.sale_resp.successdata:type_name -> internalservice.success_sale
	19, // 3: internalservice.history_resp.request:type_name -> internalservice.history
	8,  // 4: internalservice.gigservice.account_details:input_type -> internalservice.user_account_data_req
	1,  // 5: internalservice.gigservice.deposit:input_type -> internalservice.deposit_req
	3,  // 6: internalservice.gigservice.withdraw:input_type -> internalservice.withdraw_req
	2,  // 7: internalservice.gigservice.capitalraise:input_type -> internalservice.capital_raise_req
	9,  // 8: internalservice.gigservice.transfer:input_type -> internalservice.transfer_req
	10, // 9: internalservice.gigservice.sale:input_type -> internalservice.sale_req
	12, // 10: internalservice.gigservice.history:input_type -> internalservice.history_req
	11, // 11: internalservice.gigservice.opening:input_type -> internalservice.opening_req
	0,  // 12: internalservice.gigservice.createaccount:input_type -> internalservice.create_user_req
	13, // 13: internalservice.gigservice.account_details:output_type -> internalservice.user_data_resp
	20, // 14: internalservice.gigservice.deposit:output_type -> internalservice.deposit_resp
	21, // 15: internalservice.gigservice.withdraw:output_type -> internalservice.withdraw_resp
	22, // 16: internalservice.gigservice.capitalraise:output_type -> internalservice.capital_raise_resp
	16, // 17: internalservice.gigservice.transfer:output_type -> internalservice.transfer_resp
	14, // 18: internalservice.gigservice.sale:output_type -> internalservice.sale_resp
	18, // 19: internalservice.gigservice.history:output_type -> internalservice.history_resp
	17, // 20: internalservice.gigservice.opening:output_type -> internalservice.opening_resp
	5,  // 21: internalservice.gigservice.createaccount:output_type -> internalservice.create_user_resp
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internalservice_internalservice_proto_init() }
func file_internalservice_internalservice_proto_init() {
	if File_internalservice_internalservice_proto != nil {
		return
	}
	file_internalservice_internalservice_proto_msgTypes[5].OneofWrappers = []any{}
	file_internalservice_internalservice_proto_msgTypes[14].OneofWrappers = []any{}
	file_internalservice_internalservice_proto_msgTypes[16].OneofWrappers = []any{}
	file_internalservice_internalservice_proto_msgTypes[20].OneofWrappers = []any{}
	file_internalservice_internalservice_proto_msgTypes[21].OneofWrappers = []any{}
	file_internalservice_internalservice_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internalservice_internalservice_proto_rawDesc), len(file_internalservice_internalservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internalservice_internalservice_proto_goTypes,
		DependencyIndexes: file_internalservice_internalservice_proto_depIdxs,
		MessageInfos:      file_internalservice_internalservice_proto_msgTypes,
	}.Build()
	File_internalservice_internalservice_proto = out.File
	file_internalservice_internalservice_proto_goTypes = nil
	file_internalservice_internalservice_proto_depIdxs = nil
}
