// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: payments/payments.proto

package payments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MpesaPayments_InitiateStkPush_FullMethodName    = "/payments.MpesaPayments/InitiateStkPush"
	MpesaPayments_InitiateB2CPayment_FullMethodName = "/payments.MpesaPayments/InitiateB2CPayment"
	MpesaPayments_RegisterC2BUrls_FullMethodName    = "/payments.MpesaPayments/RegisterC2BUrls"
	MpesaPayments_SimulateC2BPayment_FullMethodName = "/payments.MpesaPayments/SimulateC2BPayment"
)

// MpesaPaymentsClient is the client API for MpesaPayments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MpesaPaymentsClient interface {
	// STK Push - prompt customer to pay
	InitiateStkPush(ctx context.Context, in *StkPushRequest, opts ...grpc.CallOption) (*StkPushResponse, error)
	// B2C - pay customer (returns/withdrawals)
	InitiateB2CPayment(ctx context.Context, in *B2CPaymentRequest, opts ...grpc.CallOption) (*B2CPaymentResponse, error)
	// C2B - register URLs for receiving payments
	RegisterC2BUrls(ctx context.Context, in *C2BRegisterRequest, opts ...grpc.CallOption) (*C2BRegisterResponse, error)
	// C2B Simulate - test C2B payment (sandbox only)
	SimulateC2BPayment(ctx context.Context, in *C2BSimulateRequest, opts ...grpc.CallOption) (*C2BSimulateResponse, error)
}

type mpesaPaymentsClient struct {
	cc grpc.ClientConnInterface
}

func NewMpesaPaymentsClient(cc grpc.ClientConnInterface) MpesaPaymentsClient {
	return &mpesaPaymentsClient{cc}
}

func (c *mpesaPaymentsClient) InitiateStkPush(ctx context.Context, in *StkPushRequest, opts ...grpc.CallOption) (*StkPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StkPushResponse)
	err := c.cc.Invoke(ctx, MpesaPayments_InitiateStkPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpesaPaymentsClient) InitiateB2CPayment(ctx context.Context, in *B2CPaymentRequest, opts ...grpc.CallOption) (*B2CPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(B2CPaymentResponse)
	err := c.cc.Invoke(ctx, MpesaPayments_InitiateB2CPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpesaPaymentsClient) RegisterC2BUrls(ctx context.Context, in *C2BRegisterRequest, opts ...grpc.CallOption) (*C2BRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2BRegisterResponse)
	err := c.cc.Invoke(ctx, MpesaPayments_RegisterC2BUrls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpesaPaymentsClient) SimulateC2BPayment(ctx context.Context, in *C2BSimulateRequest, opts ...grpc.CallOption) (*C2BSimulateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(C2BSimulateResponse)
	err := c.cc.Invoke(ctx, MpesaPayments_SimulateC2BPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MpesaPaymentsServer is the server API for MpesaPayments service.
// All implementations must embed UnimplementedMpesaPaymentsServer
// for forward compatibility.
type MpesaPaymentsServer interface {
	// STK Push - prompt customer to pay
	InitiateStkPush(context.Context, *StkPushRequest) (*StkPushResponse, error)
	// B2C - pay customer (returns/withdrawals)
	InitiateB2CPayment(context.Context, *B2CPaymentRequest) (*B2CPaymentResponse, error)
	// C2B - register URLs for receiving payments
	RegisterC2BUrls(context.Context, *C2BRegisterRequest) (*C2BRegisterResponse, error)
	// C2B Simulate - test C2B payment (sandbox only)
	SimulateC2BPayment(context.Context, *C2BSimulateRequest) (*C2BSimulateResponse, error)
	mustEmbedUnimplementedMpesaPaymentsServer()
}

// UnimplementedMpesaPaymentsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMpesaPaymentsServer struct{}

func (UnimplementedMpesaPaymentsServer) InitiateStkPush(context.Context, *StkPushRequest) (*StkPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateStkPush not implemented")
}
func (UnimplementedMpesaPaymentsServer) InitiateB2CPayment(context.Context, *B2CPaymentRequest) (*B2CPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateB2CPayment not implemented")
}
func (UnimplementedMpesaPaymentsServer) RegisterC2BUrls(context.Context, *C2BRegisterRequest) (*C2BRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterC2BUrls not implemented")
}
func (UnimplementedMpesaPaymentsServer) SimulateC2BPayment(context.Context, *C2BSimulateRequest) (*C2BSimulateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimulateC2BPayment not implemented")
}
func (UnimplementedMpesaPaymentsServer) mustEmbedUnimplementedMpesaPaymentsServer() {}
func (UnimplementedMpesaPaymentsServer) testEmbeddedByValue()                       {}

// UnsafeMpesaPaymentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MpesaPaymentsServer will
// result in compilation errors.
type UnsafeMpesaPaymentsServer interface {
	mustEmbedUnimplementedMpesaPaymentsServer()
}

func RegisterMpesaPaymentsServer(s grpc.ServiceRegistrar, srv MpesaPaymentsServer) {
	// If the following call pancis, it indicates UnimplementedMpesaPaymentsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MpesaPayments_ServiceDesc, srv)
}

func _MpesaPayments_InitiateStkPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StkPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpesaPaymentsServer).InitiateStkPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpesaPayments_InitiateStkPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpesaPaymentsServer).InitiateStkPush(ctx, req.(*StkPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpesaPayments_InitiateB2CPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(B2CPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpesaPaymentsServer).InitiateB2CPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpesaPayments_InitiateB2CPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpesaPaymentsServer).InitiateB2CPayment(ctx, req.(*B2CPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpesaPayments_RegisterC2BUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2BRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpesaPaymentsServer).RegisterC2BUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpesaPayments_RegisterC2BUrls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpesaPaymentsServer).RegisterC2BUrls(ctx, req.(*C2BRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpesaPayments_SimulateC2BPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2BSimulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpesaPaymentsServer).SimulateC2BPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpesaPayments_SimulateC2BPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpesaPaymentsServer).SimulateC2BPayment(ctx, req.(*C2BSimulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MpesaPayments_ServiceDesc is the grpc.ServiceDesc for MpesaPayments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MpesaPayments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.MpesaPayments",
	HandlerType: (*MpesaPaymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateStkPush",
			Handler:    _MpesaPayments_InitiateStkPush_Handler,
		},
		{
			MethodName: "InitiateB2CPayment",
			Handler:    _MpesaPayments_InitiateB2CPayment_Handler,
		},
		{
			MethodName: "RegisterC2BUrls",
			Handler:    _MpesaPayments_RegisterC2BUrls_Handler,
		},
		{
			MethodName: "SimulateC2BPayment",
			Handler:    _MpesaPayments_SimulateC2BPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/payments.proto",
}
