// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: payments/payments.proto

package payments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// STK Push Messages
type StkPushRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber      string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Amount           string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AccountReference string                 `protobuf:"bytes,3,opt,name=account_reference,json=accountReference,proto3" json:"account_reference,omitempty"`
	TransactionDesc  string                 `protobuf:"bytes,4,opt,name=transaction_desc,json=transactionDesc,proto3" json:"transaction_desc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StkPushRequest) Reset() {
	*x = StkPushRequest{}
	mi := &file_payments_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StkPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StkPushRequest) ProtoMessage() {}

func (x *StkPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StkPushRequest.ProtoReflect.Descriptor instead.
func (*StkPushRequest) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{0}
}

func (x *StkPushRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *StkPushRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *StkPushRequest) GetAccountReference() string {
	if x != nil {
		return x.AccountReference
	}
	return ""
}

func (x *StkPushRequest) GetTransactionDesc() string {
	if x != nil {
		return x.TransactionDesc
	}
	return ""
}

type StkPushResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MerchantRequestId string                 `protobuf:"bytes,3,opt,name=merchant_request_id,json=merchantRequestId,proto3" json:"merchant_request_id,omitempty"`
	CheckoutRequestId string                 `protobuf:"bytes,4,opt,name=checkout_request_id,json=checkoutRequestId,proto3" json:"checkout_request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StkPushResponse) Reset() {
	*x = StkPushResponse{}
	mi := &file_payments_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StkPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StkPushResponse) ProtoMessage() {}

func (x *StkPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StkPushResponse.ProtoReflect.Descriptor instead.
func (*StkPushResponse) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{1}
}

func (x *StkPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StkPushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StkPushResponse) GetMerchantRequestId() string {
	if x != nil {
		return x.MerchantRequestId
	}
	return ""
}

func (x *StkPushResponse) GetCheckoutRequestId() string {
	if x != nil {
		return x.CheckoutRequestId
	}
	return ""
}

// B2C Messages
type B2CPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Remarks       string                 `protobuf:"bytes,3,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Occasion      string                 `protobuf:"bytes,4,opt,name=occasion,proto3" json:"occasion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *B2CPaymentRequest) Reset() {
	*x = B2CPaymentRequest{}
	mi := &file_payments_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B2CPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2CPaymentRequest) ProtoMessage() {}

func (x *B2CPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2CPaymentRequest.ProtoReflect.Descriptor instead.
func (*B2CPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{2}
}

func (x *B2CPaymentRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *B2CPaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *B2CPaymentRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *B2CPaymentRequest) GetOccasion() string {
	if x != nil {
		return x.Occasion
	}
	return ""
}

type B2CPaymentResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Success                  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message                  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConversationId           string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	OriginatorConversationId string                 `protobuf:"bytes,4,opt,name=originator_conversation_id,json=originatorConversationId,proto3" json:"originator_conversation_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *B2CPaymentResponse) Reset() {
	*x = B2CPaymentResponse{}
	mi := &file_payments_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B2CPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2CPaymentResponse) ProtoMessage() {}

func (x *B2CPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2CPaymentResponse.ProtoReflect.Descriptor instead.
func (*B2CPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{3}
}

func (x *B2CPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *B2CPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *B2CPaymentResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *B2CPaymentResponse) GetOriginatorConversationId() string {
	if x != nil {
		return x.OriginatorConversationId
	}
	return ""
}

// C2B Register Messages
type C2BRegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationUrl string                 `protobuf:"bytes,1,opt,name=confirmation_url,json=confirmationUrl,proto3" json:"confirmation_url,omitempty"`
	ValidationUrl   string                 `protobuf:"bytes,2,opt,name=validation_url,json=validationUrl,proto3" json:"validation_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *C2BRegisterRequest) Reset() {
	*x = C2BRegisterRequest{}
	mi := &file_payments_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BRegisterRequest) ProtoMessage() {}

func (x *C2BRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BRegisterRequest.ProtoReflect.Descriptor instead.
func (*C2BRegisterRequest) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{4}
}

func (x *C2BRegisterRequest) GetConfirmationUrl() string {
	if x != nil {
		return x.ConfirmationUrl
	}
	return ""
}

func (x *C2BRegisterRequest) GetValidationUrl() string {
	if x != nil {
		return x.ValidationUrl
	}
	return ""
}

type C2BRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BRegisterResponse) Reset() {
	*x = C2BRegisterResponse{}
	mi := &file_payments_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BRegisterResponse) ProtoMessage() {}

func (x *C2BRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BRegisterResponse.ProtoReflect.Descriptor instead.
func (*C2BRegisterResponse) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{5}
}

func (x *C2BRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *C2BRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// C2B Simulate Messages
type C2BSimulateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BillRefNumber string                 `protobuf:"bytes,3,opt,name=bill_ref_number,json=billRefNumber,proto3" json:"bill_ref_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BSimulateRequest) Reset() {
	*x = C2BSimulateRequest{}
	mi := &file_payments_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BSimulateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BSimulateRequest) ProtoMessage() {}

func (x *C2BSimulateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BSimulateRequest.ProtoReflect.Descriptor instead.
func (*C2BSimulateRequest) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{6}
}

func (x *C2BSimulateRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *C2BSimulateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *C2BSimulateRequest) GetBillRefNumber() string {
	if x != nil {
		return x.BillRefNumber
	}
	return ""
}

type C2BSimulateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2BSimulateResponse) Reset() {
	*x = C2BSimulateResponse{}
	mi := &file_payments_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2BSimulateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BSimulateResponse) ProtoMessage() {}

func (x *C2BSimulateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BSimulateResponse.ProtoReflect.Descriptor instead.
func (*C2BSimulateResponse) Descriptor() ([]byte, []int) {
	return file_payments_payments_proto_rawDescGZIP(), []int{7}
}

func (x *C2BSimulateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *C2BSimulateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payments_payments_proto protoreflect.FileDescriptor

const file_payments_payments_proto_rawDesc = "" +
	"\n" +
	"\x17payments/payments.proto\x12\bpayments\"\xa3\x01\n" +
	"\x0eStkPushRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12+\n" +
	"\x11account_reference\x18\x03 \x01(\tR\x10accountReference\x12)\n" +
	"\x10transaction_desc\x18\x04 \x01(\tR\x0ftransactionDesc\"\xa5\x01\n" +
	"\x0fStkPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x13merchant_request_id\x18\x03 \x01(\tR\x11merchantRequestId\x12.\n" +
	"\x13checkout_request_id\x18\x04 \x01(\tR\x11checkoutRequestId\"\x84\x01\n" +
	"\x11B2CPaymentRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x18\n" +
	"\aremarks\x18\x03 \x01(\tR\aremarks\x12\x1a\n" +
	"\boccasion\x18\x04 \x01(\tR\boccasion\"\xaf\x01\n" +
	"\x12B2CPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12<\n" +
	"\x1aoriginator_conversation_id\x18\x04 \x01(\tR\x18originatorConversationId\"f\n" +
	"\x12C2BRegisterRequest\x12)\n" +
	"\x10confirmation_url\x18\x01 \x01(\tR\x0fconfirmationUrl\x12%\n" +
	"\x0evalidation_url\x18\x02 \x01(\tR\rvalidationUrl\"I\n" +
	"\x13C2BRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x12C2BSimulateRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12&\n" +
	"\x0fbill_ref_number\x18\x03 \x01(\tR\rbillRefNumber\"I\n" +
	"\x13C2BSimulateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcb\x02\n" +
	"\rMpesaPayments\x12F\n" +
	"\x0fInitiateStkPush\x12\x18.payments.StkPushRequest\x1a\x19.payments.StkPushResponse\x12O\n" +
	"\x12InitiateB2CPayment\x12\x1b.payments.B2CPaymentRequest\x1a\x1c.payments.B2CPaymentResponse\x12N\n" +
	"\x0fRegisterC2BUrls\x12\x1c.payments.C2BRegisterRequest\x1a\x1d.payments.C2BRegisterResponse\x12Q\n" +
	"\x12SimulateC2BPayment\x12\x1c.payments.C2BSimulateRequest\x1a\x1d.payments.C2BSimulateResponseB\fZ\n" +
	"./paymentsb\x06proto3"

var (
	file_payments_payments_proto_rawDescOnce sync.Once
	file_payments_payments_proto_rawDescData []byte
)

func file_payments_payments_proto_rawDescGZIP() []byte {
	file_payments_payments_proto_rawDescOnce.Do(func() {
		file_payments_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_payments_proto_rawDesc), len(file_payments_payments_proto_rawDesc)))
	})
	return file_payments_payments_proto_rawDescData
}

var file_payments_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payments_payments_proto_goTypes = []any{
	(*StkPushRequest)(nil),      // 0: payments.StkPushRequest
	(*StkPushResponse)(nil),     // 1: payments.StkPushResponse
	(*B2CPaymentRequest)(nil),   // 2: payments.B2CPaymentRequest
	(*B2CPaymentResponse)(nil),  // 3: payments.B2CPaymentResponse
	(*C2BRegisterRequest)(nil),  // 4: payments.C2BRegisterRequest
	(*C2BRegisterResponse)(nil), // 5: payments.C2BRegisterResponse
	(*C2BSimulateRequest)(nil),  // 6: payments.C2BSimulateRequest
	(*C2BSimulateResponse)(nil), // 7: payments.C2BSimulateResponse
}
var file_payments_payments_proto_depIdxs = []int32{
	0, // 0: payments.MpesaPayments.InitiateStkPush:input_type -> payments.StkPushRequest
	2, // 1: payments.MpesaPayments.InitiateB2CPayment:input_type -> payments.B2CPaymentRequest
	4, // 2: payments.MpesaPayments.RegisterC2BUrls:input_type -> payments.C2BRegisterRequest
	6, // 3: payments.MpesaPayments.SimulateC2BPayment:input_type -> payments.C2BSimulateRequest
	1, // 4: payments.MpesaPayments.InitiateStkPush:output_type -> payments.StkPushResponse
	3, // 5: payments.MpesaPayments.InitiateB2CPayment:output_type -> payments.B2CPaymentResponse
	5, // 6: payments.MpesaPayments.RegisterC2BUrls:output_type -> payments.C2BRegisterResponse
	7, // 7: payments.MpesaPayments.SimulateC2BPayment:output_type -> payments.C2BSimulateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payments_payments_proto_init() }
func file_payments_payments_proto_init() {
	if File_payments_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_payments_proto_rawDesc), len(file_payments_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_payments_proto_goTypes,
		DependencyIndexes: file_payments_payments_proto_depIdxs,
		MessageInfos:      file_payments_payments_proto_msgTypes,
	}.Build()
	File_payments_payments_proto = out.File
	file_payments_payments_proto_goTypes = nil
	file_payments_payments_proto_depIdxs = nil
}
