// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: paymentproto/payment.proto

package paymentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paymentservice_Deposit_FullMethodName = "/paymentproto.paymentservice/deposit"
)

// PaymentserviceClient is the client API for Paymentservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentserviceClient interface {
	Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error)
}

type paymentserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentserviceClient(cc grpc.ClientConnInterface) PaymentserviceClient {
	return &paymentserviceClient{cc}
}

func (c *paymentserviceClient) Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResp)
	err := c.cc.Invoke(ctx, Paymentservice_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentserviceServer is the server API for Paymentservice service.
// All implementations must embed UnimplementedPaymentserviceServer
// for forward compatibility.
type PaymentserviceServer interface {
	Deposit(context.Context, *DepositReq) (*DepositResp, error)
	mustEmbedUnimplementedPaymentserviceServer()
}

// UnimplementedPaymentserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentserviceServer struct{}

func (UnimplementedPaymentserviceServer) Deposit(context.Context, *DepositReq) (*DepositResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedPaymentserviceServer) mustEmbedUnimplementedPaymentserviceServer() {}
func (UnimplementedPaymentserviceServer) testEmbeddedByValue()                        {}

// UnsafePaymentserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentserviceServer will
// result in compilation errors.
type UnsafePaymentserviceServer interface {
	mustEmbedUnimplementedPaymentserviceServer()
}

func RegisterPaymentserviceServer(s grpc.ServiceRegistrar, srv PaymentserviceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paymentservice_ServiceDesc, srv)
}

func _Paymentservice_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentserviceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paymentservice_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentserviceServer).Deposit(ctx, req.(*DepositReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Paymentservice_ServiceDesc is the grpc.ServiceDesc for Paymentservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paymentservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentproto.paymentservice",
	HandlerType: (*PaymentserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deposit",
			Handler:    _Paymentservice_Deposit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentproto/payment.proto",
}
