// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gatewayproto/gateway.proto

package gatewayproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gatewayservice_Deposit_FullMethodName  = "/gatewayproto.gatewayservice/deposit"
	Gatewayservice_Withdraw_FullMethodName = "/gatewayproto.gatewayservice/withdraw"
)

// GatewayserviceClient is the client API for Gatewayservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayserviceClient interface {
	Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error)
	Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error)
}

type gatewayserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayserviceClient(cc grpc.ClientConnInterface) GatewayserviceClient {
	return &gatewayserviceClient{cc}
}

func (c *gatewayserviceClient) Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResp)
	err := c.cc.Invoke(ctx, Gatewayservice_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayserviceClient) Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawResp)
	err := c.cc.Invoke(ctx, Gatewayservice_Withdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayserviceServer is the server API for Gatewayservice service.
// All implementations must embed UnimplementedGatewayserviceServer
// for forward compatibility.
type GatewayserviceServer interface {
	Deposit(context.Context, *DepositReq) (*DepositResp, error)
	Withdraw(context.Context, *WithdrawReq) (*WithdrawResp, error)
	mustEmbedUnimplementedGatewayserviceServer()
}

// UnimplementedGatewayserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayserviceServer struct{}

func (UnimplementedGatewayserviceServer) Deposit(context.Context, *DepositReq) (*DepositResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedGatewayserviceServer) Withdraw(context.Context, *WithdrawReq) (*WithdrawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedGatewayserviceServer) mustEmbedUnimplementedGatewayserviceServer() {}
func (UnimplementedGatewayserviceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayserviceServer will
// result in compilation errors.
type UnsafeGatewayserviceServer interface {
	mustEmbedUnimplementedGatewayserviceServer()
}

func RegisterGatewayserviceServer(s grpc.ServiceRegistrar, srv GatewayserviceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gatewayservice_ServiceDesc, srv)
}

func _Gatewayservice_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayserviceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gatewayservice_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayserviceServer).Deposit(ctx, req.(*DepositReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gatewayservice_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayserviceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gatewayservice_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayserviceServer).Withdraw(ctx, req.(*WithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Gatewayservice_ServiceDesc is the grpc.ServiceDesc for Gatewayservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gatewayservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatewayproto.gatewayservice",
	HandlerType: (*GatewayserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deposit",
			Handler:    _Gatewayservice_Deposit_Handler,
		},
		{
			MethodName: "withdraw",
			Handler:    _Gatewayservice_Withdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gatewayproto/gateway.proto",
}
