// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// here we should describe the request from the api_gateway
type CreateUserReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Globaluserid     string                 `protobuf:"bytes,1,opt,name=globaluserid,proto3" json:"globaluserid,omitempty"`
	Phonenumber      string                 `protobuf:"bytes,2,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Kycstatus        string                 `protobuf:"bytes,3,opt,name=kycstatus,proto3" json:"kycstatus,omitempty"`
	Kyclevel         string                 `protobuf:"bytes,4,opt,name=kyclevel,proto3" json:"kyclevel,omitempty"`
	Acceptterms      string                 `protobuf:"bytes,5,opt,name=acceptterms,proto3" json:"acceptterms,omitempty"`
	Transactionlimit int64                  `protobuf:"varint,6,opt,name=transactionlimit,proto3" json:"transactionlimit,omitempty"`
	Username         string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Wallet           *CreateWallet          `protobuf:"bytes,8,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetGlobaluserid() string {
	if x != nil {
		return x.Globaluserid
	}
	return ""
}

func (x *CreateUserReq) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *CreateUserReq) GetKycstatus() string {
	if x != nil {
		return x.Kycstatus
	}
	return ""
}

func (x *CreateUserReq) GetKyclevel() string {
	if x != nil {
		return x.Kyclevel
	}
	return ""
}

func (x *CreateUserReq) GetAcceptterms() string {
	if x != nil {
		return x.Acceptterms
	}
	return ""
}

func (x *CreateUserReq) GetTransactionlimit() int64 {
	if x != nil {
		return x.Transactionlimit
	}
	return 0
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetWallet() *CreateWallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type CreateWallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cashbalance   string                 `protobuf:"bytes,1,opt,name=cashbalance,proto3" json:"cashbalance,omitempty"`
	Goldbalance   string                 `protobuf:"bytes,2,opt,name=goldbalance,proto3" json:"goldbalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWallet) Reset() {
	*x = CreateWallet{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWallet) ProtoMessage() {}

func (x *CreateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWallet.ProtoReflect.Descriptor instead.
func (*CreateWallet) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWallet) GetCashbalance() string {
	if x != nil {
		return x.Cashbalance
	}
	return ""
}

func (x *CreateWallet) GetGoldbalance() string {
	if x != nil {
		return x.Goldbalance
	}
	return ""
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Errors        *Changeseterrors       `protobuf:"bytes,3,opt,name=errors,proto3,oneof" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *CreateUserResp) GetErrors() *Changeseterrors {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Validationerror struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validationerror) Reset() {
	*x = Validationerror{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validationerror) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validationerror) ProtoMessage() {}

func (x *Validationerror) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validationerror.ProtoReflect.Descriptor instead.
func (*Validationerror) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Validationerror) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Validationerror) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Changeseterrors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*Validationerror     `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Changeseterrors) Reset() {
	*x = Changeseterrors{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Changeseterrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changeseterrors) ProtoMessage() {}

func (x *Changeseterrors) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changeseterrors.ProtoReflect.Descriptor instead.
func (*Changeseterrors) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Changeseterrors) GetErrors() []*Validationerror {
	if x != nil {
		return x.Errors
	}
	return nil
}

type UserAccountDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccountDataReq) Reset() {
	*x = UserAccountDataReq{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccountDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountDataReq) ProtoMessage() {}

func (x *UserAccountDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountDataReq.ProtoReflect.Descriptor instead.
func (*UserAccountDataReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *UserAccountDataReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	GoldAmount    *Amounts               `protobuf:"bytes,3,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	CashAmount    *Amounts               `protobuf:"bytes,4,opt,name=cash_amount,json=cashAmount,proto3" json:"cash_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TransferReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *TransferReq) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *TransferReq) GetGoldAmount() *Amounts {
	if x != nil {
		return x.GoldAmount
	}
	return nil
}

func (x *TransferReq) GetCashAmount() *Amounts {
	if x != nil {
		return x.CashAmount
	}
	return nil
}

type SaleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	GoldAmount    *Amounts               `protobuf:"bytes,3,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	CashAmount    *Amounts               `protobuf:"bytes,4,opt,name=cash_amount,json=cashAmount,proto3" json:"cash_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleReq) Reset() {
	*x = SaleReq{}
	mi := &file_proto_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleReq) ProtoMessage() {}

func (x *SaleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleReq.ProtoReflect.Descriptor instead.
func (*SaleReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *SaleReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *SaleReq) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *SaleReq) GetGoldAmount() *Amounts {
	if x != nil {
		return x.GoldAmount
	}
	return nil
}

func (x *SaleReq) GetCashAmount() *Amounts {
	if x != nil {
		return x.CashAmount
	}
	return nil
}

type OpeningReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningReq) Reset() {
	*x = OpeningReq{}
	mi := &file_proto_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningReq) ProtoMessage() {}

func (x *OpeningReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningReq.ProtoReflect.Descriptor instead.
func (*OpeningReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{8}
}

type HistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryReq) Reset() {
	*x = HistoryReq{}
	mi := &file_proto_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReq) ProtoMessage() {}

func (x *HistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReq.ProtoReflect.Descriptor instead.
func (*HistoryReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{9}
}

// request i am thinking should be values like get_account_amount(account_details)
// request transfering amount from one person's wallet to another(transfer)
// if they want to see any opening they can (openings)
// if they are looking for someone selling gold (sale)
// market
// history
type UserDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoldAmount    *Amounts               `protobuf:"bytes,1,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	CashAmount    *Amounts               `protobuf:"bytes,2,opt,name=cash_amount,json=cashAmount,proto3" json:"cash_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataResp) Reset() {
	*x = UserDataResp{}
	mi := &file_proto_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResp) ProtoMessage() {}

func (x *UserDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResp.ProtoReflect.Descriptor instead.
func (*UserDataResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *UserDataResp) GetGoldAmount() *Amounts {
	if x != nil {
		return x.GoldAmount
	}
	return nil
}

func (x *UserDataResp) GetCashAmount() *Amounts {
	if x != nil {
		return x.CashAmount
	}
	return nil
}

type SaleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Goldamount    *Amounts               `protobuf:"bytes,4,opt,name=goldamount,proto3" json:"goldamount,omitempty"`
	Moneyamount   *Amounts               `protobuf:"bytes,5,opt,name=moneyamount,proto3" json:"moneyamount,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,7,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleResp) Reset() {
	*x = SaleResp{}
	mi := &file_proto_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleResp) ProtoMessage() {}

func (x *SaleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleResp.ProtoReflect.Descriptor instead.
func (*SaleResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *SaleResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaleResp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SaleResp) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SaleResp) GetGoldamount() *Amounts {
	if x != nil {
		return x.Goldamount
	}
	return nil
}

func (x *SaleResp) GetMoneyamount() *Amounts {
	if x != nil {
		return x.Moneyamount
	}
	return nil
}

func (x *SaleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaleResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// for gold every
type TransferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TranserId     string                 `protobuf:"bytes,1,opt,name=transer_id,json=transerId,proto3" json:"transer_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	GoldAmount    *Amounts               `protobuf:"bytes,4,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
	MoneyAmount   *Amounts               `protobuf:"bytes,5,opt,name=money_amount,json=moneyAmount,proto3" json:"money_amount,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Reason        *string                `protobuf:"bytes,7,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	mi := &file_proto_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *TransferResp) GetTranserId() string {
	if x != nil {
		return x.TranserId
	}
	return ""
}

func (x *TransferResp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferResp) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferResp) GetGoldAmount() *Amounts {
	if x != nil {
		return x.GoldAmount
	}
	return nil
}

func (x *TransferResp) GetMoneyAmount() *Amounts {
	if x != nil {
		return x.MoneyAmount
	}
	return nil
}

func (x *TransferResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResp) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// opening
type OpeningResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *Amounts               `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ClosingDate   string                 `protobuf:"bytes,2,opt,name=closing_date,json=closingDate,proto3" json:"closing_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningResp) Reset() {
	*x = OpeningResp{}
	mi := &file_proto_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningResp) ProtoMessage() {}

func (x *OpeningResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningResp.ProtoReflect.Descriptor instead.
func (*OpeningResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *OpeningResp) GetAmount() *Amounts {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *OpeningResp) GetClosingDate() string {
	if x != nil {
		return x.ClosingDate
	}
	return ""
}

type HistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []*History             `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResp) Reset() {
	*x = HistoryResp{}
	mi := &file_proto_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResp) ProtoMessage() {}

func (x *HistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResp.ProtoReflect.Descriptor instead.
func (*HistoryResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *HistoryResp) GetRequest() []*History {
	if x != nil {
		return x.Request
	}
	return nil
}

type History struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpeningDate       string                 `protobuf:"bytes,1,opt,name=opening_date,json=openingDate,proto3" json:"opening_date,omitempty"`
	ClosingDate       string                 `protobuf:"bytes,2,opt,name=closing_date,json=closingDate,proto3" json:"closing_date,omitempty"`
	InitialInv        *Amounts               `protobuf:"bytes,3,opt,name=initial_inv,json=initialInv,proto3" json:"initial_inv,omitempty"`
	Revenue           *Amounts               `protobuf:"bytes,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	PeopleInv         int64                  `protobuf:"varint,5,opt,name=people_inv,json=peopleInv,proto3" json:"people_inv,omitempty"`
	ProfitPerShilling *Amounts               `protobuf:"bytes,6,opt,name=profit_per_shilling,json=profitPerShilling,proto3" json:"profit_per_shilling,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_proto_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *History) GetOpeningDate() string {
	if x != nil {
		return x.OpeningDate
	}
	return ""
}

func (x *History) GetClosingDate() string {
	if x != nil {
		return x.ClosingDate
	}
	return ""
}

func (x *History) GetInitialInv() *Amounts {
	if x != nil {
		return x.InitialInv
	}
	return nil
}

func (x *History) GetRevenue() *Amounts {
	if x != nil {
		return x.Revenue
	}
	return nil
}

func (x *History) GetPeopleInv() int64 {
	if x != nil {
		return x.PeopleInv
	}
	return 0
}

func (x *History) GetProfitPerShilling() *Amounts {
	if x != nil {
		return x.ProfitPerShilling
	}
	return nil
}

type Amounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amounts) Reset() {
	*x = Amounts{}
	mi := &file_proto_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amounts) ProtoMessage() {}

func (x *Amounts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amounts.ProtoReflect.Descriptor instead.
func (*Amounts) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *Amounts) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\x04auth\"\xa8\x02\n" +
	"\x0fcreate_user_req\x12\"\n" +
	"\fglobaluserid\x18\x01 \x01(\tR\fglobaluserid\x12 \n" +
	"\vphonenumber\x18\x02 \x01(\tR\vphonenumber\x12\x1c\n" +
	"\tkycstatus\x18\x03 \x01(\tR\tkycstatus\x12\x1a\n" +
	"\bkyclevel\x18\x04 \x01(\tR\bkyclevel\x12 \n" +
	"\vacceptterms\x18\x05 \x01(\tR\vacceptterms\x12*\n" +
	"\x10transactionlimit\x18\x06 \x01(\x03R\x10transactionlimit\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12+\n" +
	"\x06wallet\x18\b \x01(\v2\x13.auth.create_walletR\x06wallet\"S\n" +
	"\rcreate_wallet\x12 \n" +
	"\vcashbalance\x18\x01 \x01(\tR\vcashbalance\x12 \n" +
	"\vgoldbalance\x18\x02 \x01(\tR\vgoldbalance\"\x94\x01\n" +
	"\x10create_user_resp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x122\n" +
	"\x06errors\x18\x03 \x01(\v2\x15.auth.changeseterrorsH\x01R\x06errors\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_errors\"A\n" +
	"\x0fvalidationerror\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x0fchangeseterrors\x12-\n" +
	"\x06errors\x18\x01 \x03(\v2\x15.auth.validationerrorR\x06errors\"'\n" +
	"\x15user_account_data_req\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9c\x01\n" +
	"\ftransfer_req\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12.\n" +
	"\vgold_amount\x18\x03 \x01(\v2\r.auth.amountsR\n" +
	"goldAmount\x12.\n" +
	"\vcash_amount\x18\x04 \x01(\v2\r.auth.amountsR\n" +
	"cashAmount\"\x98\x01\n" +
	"\bsale_req\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12.\n" +
	"\vgold_amount\x18\x03 \x01(\v2\r.auth.amountsR\n" +
	"goldAmount\x12.\n" +
	"\vcash_amount\x18\x04 \x01(\v2\r.auth.amountsR\n" +
	"cashAmount\"\r\n" +
	"\vopening_req\"\r\n" +
	"\vhistory_req\"p\n" +
	"\x0euser_data_resp\x12.\n" +
	"\vgold_amount\x18\x01 \x01(\v2\r.auth.amountsR\n" +
	"goldAmount\x12.\n" +
	"\vcash_amount\x18\x02 \x01(\v2\r.auth.amountsR\n" +
	"cashAmount\"\xe1\x01\n" +
	"\tsale_resp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12-\n" +
	"\n" +
	"goldamount\x18\x04 \x01(\v2\r.auth.amountsR\n" +
	"goldamount\x12/\n" +
	"\vmoneyamount\x18\x05 \x01(\v2\r.auth.amountsR\vmoneyamount\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\a \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\xf6\x01\n" +
	"\rtransfer_resp\x12\x1d\n" +
	"\n" +
	"transer_id\x18\x01 \x01(\tR\ttranserId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12.\n" +
	"\vgold_amount\x18\x04 \x01(\v2\r.auth.amountsR\n" +
	"goldAmount\x120\n" +
	"\fmoney_amount\x18\x05 \x01(\v2\r.auth.amountsR\vmoneyAmount\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1b\n" +
	"\x06reason\x18\a \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"X\n" +
	"\fopening_resp\x12%\n" +
	"\x06amount\x18\x01 \x01(\v2\r.auth.amountsR\x06amount\x12!\n" +
	"\fclosing_date\x18\x02 \x01(\tR\vclosingDate\"7\n" +
	"\fhistory_resp\x12'\n" +
	"\arequest\x18\x01 \x03(\v2\r.auth.historyR\arequest\"\x86\x02\n" +
	"\ahistory\x12!\n" +
	"\fopening_date\x18\x01 \x01(\tR\vopeningDate\x12!\n" +
	"\fclosing_date\x18\x02 \x01(\tR\vclosingDate\x12.\n" +
	"\vinitial_inv\x18\x03 \x01(\v2\r.auth.amountsR\n" +
	"initialInv\x12'\n" +
	"\arevenue\x18\x04 \x01(\v2\r.auth.amountsR\arevenue\x12\x1d\n" +
	"\n" +
	"people_inv\x18\x05 \x01(\x03R\tpeopleInv\x12=\n" +
	"\x13profit_per_shilling\x18\x06 \x01(\v2\r.auth.amountsR\x11profitPerShilling\"!\n" +
	"\aamounts\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount2\xd4\x02\n" +
	"\n" +
	"gigservice\x12D\n" +
	"\x0faccount_details\x12\x1b.auth.user_account_data_req\x1a\x14.auth.user_data_resp\x123\n" +
	"\btransfer\x12\x12.auth.transfer_req\x1a\x13.auth.transfer_resp\x12'\n" +
	"\x04sale\x12\x0e.auth.sale_req\x1a\x0f.auth.sale_resp\x120\n" +
	"\ahistory\x12\x11.auth.history_req\x1a\x12.auth.history_resp\x120\n" +
	"\aopening\x12\x11.auth.opening_req\x1a\x12.auth.opening_resp\x12>\n" +
	"\rcreateaccount\x12\x15.auth.create_user_req\x1a\x16.auth.create_user_respB\tZ\a./protob\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_gateway_proto_goTypes = []any{
	(*CreateUserReq)(nil),      // 0: auth.create_user_req
	(*CreateWallet)(nil),       // 1: auth.create_wallet
	(*CreateUserResp)(nil),     // 2: auth.create_user_resp
	(*Validationerror)(nil),    // 3: auth.validationerror
	(*Changeseterrors)(nil),    // 4: auth.changeseterrors
	(*UserAccountDataReq)(nil), // 5: auth.user_account_data_req
	(*TransferReq)(nil),        // 6: auth.transfer_req
	(*SaleReq)(nil),            // 7: auth.sale_req
	(*OpeningReq)(nil),         // 8: auth.opening_req
	(*HistoryReq)(nil),         // 9: auth.history_req
	(*UserDataResp)(nil),       // 10: auth.user_data_resp
	(*SaleResp)(nil),           // 11: auth.sale_resp
	(*TransferResp)(nil),       // 12: auth.transfer_resp
	(*OpeningResp)(nil),        // 13: auth.opening_resp
	(*HistoryResp)(nil),        // 14: auth.history_resp
	(*History)(nil),            // 15: auth.history
	(*Amounts)(nil),            // 16: auth.amounts
}
var file_proto_gateway_proto_depIdxs = []int32{
	1,  // 0: auth.create_user_req.wallet:type_name -> auth.create_wallet
	4,  // 1: auth.create_user_resp.errors:type_name -> auth.changeseterrors
	3,  // 2: auth.changeseterrors.errors:type_name -> auth.validationerror
	16, // 3: auth.transfer_req.gold_amount:type_name -> auth.amounts
	16, // 4: auth.transfer_req.cash_amount:type_name -> auth.amounts
	16, // 5: auth.sale_req.gold_amount:type_name -> auth.amounts
	16, // 6: auth.sale_req.cash_amount:type_name -> auth.amounts
	16, // 7: auth.user_data_resp.gold_amount:type_name -> auth.amounts
	16, // 8: auth.user_data_resp.cash_amount:type_name -> auth.amounts
	16, // 9: auth.sale_resp.goldamount:type_name -> auth.amounts
	16, // 10: auth.sale_resp.moneyamount:type_name -> auth.amounts
	16, // 11: auth.transfer_resp.gold_amount:type_name -> auth.amounts
	16, // 12: auth.transfer_resp.money_amount:type_name -> auth.amounts
	16, // 13: auth.opening_resp.amount:type_name -> auth.amounts
	15, // 14: auth.history_resp.request:type_name -> auth.history
	16, // 15: auth.history.initial_inv:type_name -> auth.amounts
	16, // 16: auth.history.revenue:type_name -> auth.amounts
	16, // 17: auth.history.profit_per_shilling:type_name -> auth.amounts
	5,  // 18: auth.gigservice.account_details:input_type -> auth.user_account_data_req
	6,  // 19: auth.gigservice.transfer:input_type -> auth.transfer_req
	7,  // 20: auth.gigservice.sale:input_type -> auth.sale_req
	9,  // 21: auth.gigservice.history:input_type -> auth.history_req
	8,  // 22: auth.gigservice.opening:input_type -> auth.opening_req
	0,  // 23: auth.gigservice.createaccount:input_type -> auth.create_user_req
	10, // 24: auth.gigservice.account_details:output_type -> auth.user_data_resp
	12, // 25: auth.gigservice.transfer:output_type -> auth.transfer_resp
	11, // 26: auth.gigservice.sale:output_type -> auth.sale_resp
	14, // 27: auth.gigservice.history:output_type -> auth.history_resp
	13, // 28: auth.gigservice.opening:output_type -> auth.opening_resp
	2,  // 29: auth.gigservice.createaccount:output_type -> auth.create_user_resp
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	file_proto_gateway_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_gateway_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_gateway_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
