// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: gatewayproto/gateway.proto

package gatewayproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phonenumber   string                 `protobuf:"bytes,1,opt,name=Phonenumber,proto3" json:"Phonenumber,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Accref        string                 `protobuf:"bytes,3,opt,name=Accref,proto3" json:"Accref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_gatewayproto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayproto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_gatewayproto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *DepositReq) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *DepositReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DepositReq) GetAccref() string {
	if x != nil {
		return x.Accref
	}
	return ""
}

type DepositResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResp) Reset() {
	*x = DepositResp{}
	mi := &file_gatewayproto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResp) ProtoMessage() {}

func (x *DepositResp) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayproto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResp.ProtoReflect.Descriptor instead.
func (*DepositResp) Descriptor() ([]byte, []int) {
	return file_gatewayproto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *DepositResp) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_gatewayproto_gateway_proto protoreflect.FileDescriptor

const file_gatewayproto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1agatewayproto/gateway.proto\x12\fgatewayproto\"_\n" +
	"\vdeposit_req\x12 \n" +
	"\vPhonenumber\x18\x01 \x01(\tR\vPhonenumber\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\tR\x06Amount\x12\x16\n" +
	"\x06Accref\x18\x03 \x01(\tR\x06Accref\"(\n" +
	"\fdeposit_resp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccess2R\n" +
	"\x0egatewayservice\x12@\n" +
	"\adeposit\x12\x19.gatewayproto.deposit_req\x1a\x1a.gatewayproto.deposit_respB\x10Z\x0e./gatewayprotob\x06proto3"

var (
	file_gatewayproto_gateway_proto_rawDescOnce sync.Once
	file_gatewayproto_gateway_proto_rawDescData []byte
)

func file_gatewayproto_gateway_proto_rawDescGZIP() []byte {
	file_gatewayproto_gateway_proto_rawDescOnce.Do(func() {
		file_gatewayproto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gatewayproto_gateway_proto_rawDesc), len(file_gatewayproto_gateway_proto_rawDesc)))
	})
	return file_gatewayproto_gateway_proto_rawDescData
}

var file_gatewayproto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gatewayproto_gateway_proto_goTypes = []any{
	(*DepositReq)(nil),  // 0: gatewayproto.deposit_req
	(*DepositResp)(nil), // 1: gatewayproto.deposit_resp
}
var file_gatewayproto_gateway_proto_depIdxs = []int32{
	0, // 0: gatewayproto.gatewayservice.deposit:input_type -> gatewayproto.deposit_req
	1, // 1: gatewayproto.gatewayservice.deposit:output_type -> gatewayproto.deposit_resp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gatewayproto_gateway_proto_init() }
func file_gatewayproto_gateway_proto_init() {
	if File_gatewayproto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gatewayproto_gateway_proto_rawDesc), len(file_gatewayproto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gatewayproto_gateway_proto_goTypes,
		DependencyIndexes: file_gatewayproto_gateway_proto_depIdxs,
		MessageInfos:      file_gatewayproto_gateway_proto_msgTypes,
	}.Build()
	File_gatewayproto_gateway_proto = out.File
	file_gatewayproto_gateway_proto_goTypes = nil
	file_gatewayproto_gateway_proto_depIdxs = nil
}
